### ISSUE TITLE
Direct Deposit

### ISSUE THREAD

**Issue by Tetronas** [BayAreaRP/v1-Reborn#15]

**Comment by Tetronas** [comment]
Direct deposit as an option
For balance, possibly a per paycheck fee to discourage

**Comment by SloppyShovel** [comment]
Can you elaborate on what this entitles

**Comment by Tetronas** [comment]
Current System: Paycheck is deposited into a holding account at the primary bank in north LS. Paycheck is gathered by going to the bank to retrieve

Suggested System: Paycheck is deposited directly into the player/character's account. Optionally, a fee is garnished from the paycheck as a "convenience fee"

**Comment by SloppyShovel** [comment]
Made intended that way,
