### ISSUE TITLE
Trucking Job Bug

### ISSUE THREAD

**Issue by Tetronas** [BayAreaRP/v1-Reborn#42]

**Comment by Tetronas** [comment]
Trucking Job: The menu to get the vehicle just says "undefined" and selecting it open an invisible menu with seeable options.

![image](https://user-images.githubusercontent.com/56986472/164130306-dd5bd61e-661c-4a34-a2c9-4a0555150678.png)

**Comment by SloppyShovel** [comment]
Removed, Getting rewritten in the future or replaced.
