### ISSUE TITLE
Keybind Conflict "x"

### ISSUE THREAD

**Issue by Tetronas** [BayAreaRP/v1-Reborn#6]

**Comment by Tetronas** [comment]
"X" Keybind conflicts with Hydraulics 

![image](https://user-images.githubusercontent.com/56986472/164126611-2f134ae6-012c-4537-9eef-c8a1201ab721.png)
![image](https://user-images.githubusercontent.com/56986472/164126620-23d7712a-b1d8-4e0a-bbee-2b29074ed618.png)

**Comment by SloppyShovel** [comment]
Change keybinds, this is native.
