### ISSUE TITLE
Ad Categories fail to filter

### ISSUE THREAD

**Issue by Tetronas** [BayAreaRP/v1-Reborn#61]
When an ad is created in a category, ad's outside of Police appear to filter to "All Advertisements" rather than to the specific category that they were posted.

**Comment by Tetronas** [comment]
![image](https://user-images.githubusercontent.com/56986472/165654569-903afbd4-d34b-4441-8cee-0ddaa89f37bc.png)

**Comment by Tetronas** [comment]
![image](https://user-images.githubusercontent.com/56986472/165654583-24e226db-d3e9-4896-9631-07663eb5da9c.png)

**Comment by SloppyShovel** [comment]
This works fine, misunderstanding on how it works, the category is locked to the job, aka if you are a police officer you can post in the category, you can't select a category and post in it not how it works.
