### ISSUE TITLE
While Incapacitated...

### ISSUE THREAD

**Issue by Tetronas** [BayAreaRP/v1-Reborn#9]

**Comment by Tetronas** [comment]
![Untitled](https://user-images.githubusercontent.com/56986472/164124002-931b6b99-30e8-4c3b-8137-9d703ced8b70.png)

**Comment by Tetronas** [comment]
You will bleed out in “x” seconds, you can be helped

press {G} to request help

Clip over

**Comment by SloppyShovel** [comment]
Fixed
